Fix broken McAfee links
OWASP/OWASP-VWAD pull request #126
Opened 2021-03-12 21:03 UTC by IPv4v6

2021-03-12 21:37 UTC, kingthorin commented
Are you sure these aren’t actually still available from McAfee via different URLs?

2021-03-16 22:24 UTC, IPv4v6 commented
It seems, McAfee removed the hackable applications and I wasn't able to find these on McAfee's website.

2021-03-17 14:52 UTC, kingthorin requested changes
Use of the Wayback Machine seems un-necesary, they're all still available from the referenced links.

2021-03-17 14:52 UTC, kingthorin commented on src/data/offline.json
> +				"url": "http://web.archive.org/web/20130204025614if_/http://downloadcenter.mcafee.com/products/tools/foundstone/hacmebank2_install.zip"
```suggestion
				"url": "http://downloadcenter.mcafee.com/products/tools/foundstone/hacmebank2_install.zip"

```

2021-03-17 14:52 UTC, kingthorin commented on src/data/offline.json
> +				"url": "http://web.archive.org/web/20130924075344if_/http://b2b-download.mcafee.com/products/tools/foundstone/hacmebooks2_installer.zip"
```suggestion
				"url": "http://b2b-download.mcafee.com/products/tools/foundstone/hacmebooks2_installer.zip"

```

2021-03-17 14:52 UTC, kingthorin commented on src/data/offline.json
> +				"url": "http://web.archive.org/web/20130204042019if_/http://downloadcenter.mcafee.com/products/tools/foundstone/hacmecasino_installer.zip"
```suggestion
				"url": "http://downloadcenter.mcafee.com/products/tools/foundstone/hacmecasino_installer.zip"

```

2021-03-17 14:52 UTC, kingthorin commented on src/data/offline.json
> +				"url": "http://web.archive.org/web/20130204042010if_/http://downloadcenter.mcafee.com/products/tools/foundstone/hacmeshipping.zip"
```suggestion
				"url": "http://downloadcenter.mcafee.com/products/tools/foundstone/hacmeshipping.zip"

```

2021-03-17 14:52 UTC, kingthorin commented on src/data/offline.json
> +				"url": "http://web.archive.org/web/20130204042023if_/http://downloadcenter.mcafee.com/products/tools/foundstone/hacmetravel_install.zip"
```suggestion
				"url": "http://downloadcenter.mcafee.com/products/tools/foundstone/hacmetravel_install.zip"

```

2021-03-22 20:58 UTC, kingthorin approved these changes

2021-03-22 20:59 UTC, merged